name: CI Test

on:
  push:
    branches:
    - main

jobs:
  deployment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run eslint
      - name: Unit Test
        run: npm test
      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          command: npm run test:e2e
          start: npm run start-dev
          wait-on: http://localhost:3000
          browser: chrome